### ISSUE TITLE
[FEATURE] Support filtering in Submissions list endpoint

### ISSUE THREAD

**Issue by dspetrov** [endatix/endatix#250]
## **Description**
Submissions list endpoint needs to have the ability to filter by `IsComplete`, `Status` and `CompletedAt`. Follow the schema defined in #248 and implement the filtering.

## **Implementation Notes**
Changes are needed in the endpoint request schema. Introduce classes (for the schema changes and it's validation needs) that support the filtering and use them for Submissions list. They can be reused for the filtering of other entities.
Make the necessary changes in the core and DB access logic to return the filtered records.

## **Acceptance Criteria**
- [x] Submissions list endpoint can return data filtered by `IsComplete`, `Status` and `CompletedAt`
- [x] The filtering classes and logic are abstracted where possible so they can be reused for other entities

## **Tasks**
- [x] Submissions list endpoint schema changes
- [x] Apply filtering logic
