### ISSUE TITLE
[FEATURE] Slack notification message integration

### ISSUE THREAD

**Issue by orilux** [endatix/endatix#289]
## **Description**
When a new form has been submitted a notification message needs to be posted into a specified Slack channel. The Slack message should contain a link to the submission details screen with the Endatix Hub.

### Slack Docs
A Slack App will need to be registered: https://api.slack.com/apps. The webhooks documentation is available here: https://api.slack.com/messaging/webhooks
### Quick implementation
The first part of the webhook article suggests that the webhook address can be generated manually. This flow can be phase 1 of the project.
The notification message should be static.
### Long-term implementation
The webhook URLs can be created programmatically (https://api.slack.com/messaging/webhooks#incoming_webhooks_programmatic)
The notification message is dynamic and contains placeholders. For example "New submission for {FormName} on {SubmittedOn}."
### Settings
- Store the notification message string in the settings
- Store the manually configured webhook address in the settings (not sure that is necessary)
### Workflow
1. Form submitter clicks "Complete".
2. Message is posted in the specified Slack channel
## **Tasks**
- [ ] Config infrastructure (API keys, etc.)
- [ ] Create Slack HTTP client
- [ ] Implement Slack notification in event handler

## **Acceptance Criteria**
- [ ] Slack App is created
- [ ] A webhook address can be configured manually (auto-generation is a nice-to-have)
- [ ] New form submissions trigger an automatic message in Slack
