### ISSUE TITLE
[FEATURE] Style SurveyJS Creator

### ISSUE THREAD

**Issue by orilux** [endatix/endatix#291]
## **Description**
Fix CSS issues with SurveyJS creator, reported here https://github.com/endatix/endatix/issues/207. Create a custom color theme for SurveyJS creator to be harmonized with the Endatix color scheme.

## **Implementation Notes**
SurveyJS Creator Component for NextJS, which is compatible with Tailwind (provided by SJS):

```
'use client';

import { useState } from "react";
import { ICreatorOptions } from "survey-creator-core";
import { SurveyCreatorComponent, SurveyCreator } from "survey-creator-react";
import "survey-core/defaultV2.css";
import "survey-creator-core/survey-creator-core.css";
import * as themes from "survey-creator-core/themes"; // import themes

import { json as defaultJson } from "../data/survey_json";
 

const defaultCreatorOptions: ICreatorOptions = {
  showLogicTab: true,
  showTranslationTab: true
};

export default function SurveyCreatorWidget(props: { json?: Object, options?: ICreatorOptions }) {

  let [creator, setCreator] = useState<SurveyCreator>();

  if (!creator) {
    creator = new SurveyCreator(props.options || defaultCreatorOptions);
    creator.applyTheme(themes.DefaultLight); // apply theme to creator instance
    creator.saveSurveyFunc = (no: number, callback: (num: number, status: boolean) => void) => {
      console.log(JSON.stringify(creator?.JSON));
      callback(no, true);
    };
    setCreator(creator);
  }

  creator.JSON = props.json || defaultJson;
 
  return (
    <div style={{ height: "80vh", width: "100%" }}>
      <SurveyCreatorComponent creator={creator} />
    </div>
  );
}
```

Additionally a custom Endatix color theme should be defined in order to harmonize the colors within the app. Docs on customizing the colors can be found here: https://surveyjs.io/survey-creator/examples/edit-user-interface-theme-with-custom-css/reactjs

A sample color palette for the creator:
```
/* SurveyJS Creator V2 */
    --primary: #1ab7fa;
    --primary-light: rgba(26, 183, 250, 0.1);
    --foreground: #ededed;
    --primary-foreground: #ffffff;
    --secondary: #1ab7fa;
    --background: #555555;
    --background-dim: #4d4d4d;
    --background-dim-light: #4d4d4d;
```

## **Acceptance Criteria**
List the specific criteria that must be met for the feature to be considered complete:

- [ ] SurveyJS Creator appears correctly
- [ ] SurveyJS Creator is styled with the Endatix colors

## **Tasks**
Break down the work into actionable tasks:

- [ ] Implement the provided fix
- [ ] Create an Endatix theme
