### ISSUE TITLE
[FEATURE] File storage (CDN)

### ISSUE THREAD

**Issue by orilux** [endatix/endatix#297]
## **Description**
Form designers as well as form submitters have a need to work with files in various situations:
### Designers

- Add a logo to the form by using the SurveyJS logo feature
- Include marketing or instructional images by using the SurveyJS “image” widget
- Create multiple choice questions where the responded has to pick one or more of the displayed images
- Custom widgets where the responded has to annotate an image

### Submitters
Form submitters have a need to upload files of various types, including images, scanned documents, PDFs, MS Word files, etc. That is achieved through the SurveyJS file upload widget.

#### Performance
Since SurveyJS stores files as part of its JSON docs in BASE64 format, that means that the JSON payload can get very large and introduce significant lag both when loading a form and when transferring a submission to the server. This can be critical with the partial submit mechanism in place.
#### Storage
Storing images within the database is not efficient.
#### Scalability
Breaking file storage out into a separate app will have scalability benefits.

## **Implementation Notes**
Implement in  phases:
### Phase 1 - Submitters use case
Cover the needs of a public user filling out a form or survey that requires images or other files to be uploaded.
### Phase 2 - Form designer use case
Use the same storage infrastructure to implement image handling within SurveyJS Creator.

## Technical Reference
Use the [onValueChanged ](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#onValueChanged) event within SurveyJS to intercept file uploads.

## Considerations

- In the first iteration uploaded files will not be available for public access or sharing
- Use Azure Blob storage
- Consider a file’s lifecycle? Delete it automatically when the submission is deleted.
- Consider expiration of images of incomplete submissions?
- File permissions should match the permissions of the submission record.
- Consider the ability of images and files to be changed before the submission of the form.
- Investigate scaling down images by size? (Full size images should be available in higher tiers)
- Consider compression of other file types?
- Consider scanning files for malware
- Consider a script for cleaning up orphaned files

## **Acceptance Criteria**
List the specific criteria that must be met for the feature to be considered complete:

- [x] Files can be uploaded as apart of a form submission, without being stored as BASE64 strings within the JSON payload of the submission
- [x] Uploaded files can be read and rendered within the submission view screen
- [] Uploaded files can be deleted

## **Tasks**

- [x] #354
- [x] Implement an upload progress bar
- [x] Enforce upload limit by file size (SurveyJS feature)
- [x] Enforce file question to use remote images by default (not manual as of today)
- [x] Clean up deleted files not associated with a form (form content) or submission (user files)
- [x] Create an endpoint for creating a new file record
- [x] Create an endpoint for reading a file record
- [x] Downsize images by scaling their dimensions down proportionally
- [x] Handle the case where the submitter deletes the uploaded file and adds a new one in its place
- [x] #328
- [x] https://github.com/endatix/endatix-private/issues/34
