### ISSUE TITLE
[FEATURE] Forms taxonomy

### ISSUE THREAD

**Issue by orilux** [endatix/endatix#343]
## **Description**
To improve the organization of a large number of forms a tagging feature must be added. Tags can be made up of one or more words and more than one tag can be added to a form. The form management screen should allow filtering by one or more tags. 

### Nice to have

- The selected tags should appear in the URL so that links to a filtered form management screen should be easy to share.
- A screen for deleting or renaming existing tags

### Future considerations
A "category" feature request is possible in the future. Categories differ from tags in two aspects:

1. A form can only have one category
2. Categories have their own navigation, as opposed to being a filtering parameter

Categories are not the goal of this task, but one of the architectural possibilities for their implementation is to share the tags schema with them (e.g. "IsCategory" flag on the Tags table).

## **Implementation Notes**
A minimum of two tables should be added to the schema:

- One table holds the list of unique tags and their ids
- One table holds the many-to-many cross-reference records between Tags and Forms (EF will auto-generate)

## **Acceptance Criteria**

- [ ] One or more tags can be assigned to a form
- [ ] The tag selection box offers autocomplete
- [ ] If a typed tag does not exist it gets auto-created
- [ ] A filter on the forms page allows you to select one or more tags

## **Tasks**
Break down the work into actionable tasks:

- [ ] Research tag best practices
     - [ ] Min and max length?
     - [ ] Should we allow different alphabets?
     - [ ] Should we enforce letter capitalization?
- [ ] Create UI mockups
- [ ] Add schema and CRUD endpoints for tags
- [ ] Implement tag filtering within the existing Forms GET endpoints
- [ ] Build tag assignment UI
- [ ] Build tag filtering UI
