### ISSUE TITLE
SPIKE: CLI Tools for creating Endatix App

### ISSUE THREAD

**Issue by PeterMarinov** [endatix/endatix#74]
# Problem
Current setup experience is far from great and we need to really improve it to follow our mission to provide developers with state of art tools and solutions. Right no developers need to follow a process of few steps with a lot of code to copy and paste and which each new feature we will add steps and complexity will increase overwhelming developers and making the "Getting Started Guide" frustrating and tedious.

# Proposed Solution

In the .NET world there are few options we can choose from, but they are far from optimal and take a lot of effort. These tools are:

| Tool | Description | Pros | Cons |
| -------- | ------- | -------- | ------- |
| **Installer** | Create native or Electron installer, which will provide wizard for the setup and  | <ul><li>potential for great for UI</li><li>will solve the problem if we provide intuitive interface</li></ul> | <ul><li>It will be hard to create this cross-platform </li><li> is overkill in many cases. </li><li> issues for companies to install new software in corp networks </li><li> not CI/CD or cloud friendly </li><li> harder release and testing effort, e.g. each OS and etc.</li><li> new installs are scary for many people. Why so hard?</li></ul>|
| **Dotnet template** | Use dotnet tools and create a new template. Link [here](https://learn.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-template-package?pivots=dotnet-8-0). This is what Umbraco are [using](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install) and is much better than what we have now | <ul><li>Very easy to develop.</li><li>Will greatly simplify current process</li></ul> | <ul><li>dotnet templates are not interactive. They support parameters, but there's not interaction on the CLI at least to my knowledge (please confirm this to be sure)</li><li>Limited customization options</li><li>They will still require some sort of UI wizard to setup connection string and other elements of the setup</li><li>Developers still need to install the template before they can use it</li></ul> |
| **Custom CLI tool** | Use something like nextjs [create-next-app CLI tool](https://nextjs.org/docs/getting-started/installation), where users are presented with interactive CLI capable of taking multiple-choice, yes/no and text questions to provide setup guidance. We can use the approach and call smth like `npx create-endatix-app` to initiate the process. | <ul><li>Great UX</li><li>Familiar to many devs outside .NET</li><li>Can be extended to install NPM packages, e.g. UI, typescript and etc.</li><li>Zero install with npx</li><li>CI/CD Cloud friendly</li><li>Can be good source of positive vibes and love for the project</li></ul> | <ul><li>Not very typical for .NET developers</li><li>Might have technical limitations</li><li>Might be more effort than anticipated</li></ul> |

What we can do further is to create CLI Tool to improve the experience

# Further Read

* https://github.com/mayuki/Cocona - might be good .NET alternative to create CLI
* `dotnet tool install --global dotnet-ef` - we can review EF CLI tools to see if it offers needed level of interaction. [Here](https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create) is how to develop such tools too
* Here is the source of the [Create Next.js App](https://github.com/vercel/next.js/blob/canary/packages/create-next-app/create-app.ts)
* Another NPM CLI tool, which is great - https://github.com/nicoalbanese/kirimase

# Tasks

- [ ] Research if dotnet templates can provide interfaction needed - e.g. select DB type, setup connection string or it's all static or predefined...
- [ ] Research if EF CLI tools can offer the interactive capability required
- [ ] Create sample [dotnet template package ](https://learn.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-template-package?pivots=dotnet-8-0)
- [ ] Create sample npm package that can be run with zero install e.g. `npx create-endatix-app`
